//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public Broker()
        {
            this.Dispatchers = new HashSet<Dispatcher>();
            this.Drivers = new HashSet<Driver>();
            this.DriverSchedules = new HashSet<DriverSchedule>();
            this.TravelSegments = new HashSet<TravelSegment>();
            this.StandbySegments = new HashSet<StandbySegment>();
            this.Users = new HashSet<User>();
            this.Vehicles = new HashSet<Vehicle>();
            this.VehicleSchedules = new HashSet<VehicleSchedule>();
        }
    
        public int BrokerId { get; set; }
        public string Name { get; set; }
        public Nullable<int> HomeLocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Dispatcher> Dispatchers { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<DriverSchedule> DriverSchedules { get; set; }
        public virtual ICollection<TravelSegment> TravelSegments { get; set; }
        public virtual ICollection<StandbySegment> StandbySegments { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<VehicleSchedule> VehicleSchedules { get; set; }
    }
}
