//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatcher
    {
        public Dispatcher()
        {
            this.Users = new HashSet<User>();
            this.DriverSchedules = new HashSet<DriverSchedule>();
            this.VehicleSchedules = new HashSet<VehicleSchedule>();
        }
    
        public int DispatcherId { get; set; }
        public string DispatcherHandle { get; set; }
        public string Name { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<DriverSchedule> DriverSchedules { get; set; }
        public virtual ICollection<VehicleSchedule> VehicleSchedules { get; set; }
    }
}
