//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.DriverSchedules = new HashSet<DriverSchedule>();
            this.TravelSegments = new HashSet<TravelSegment>();
            this.StandbySegments = new HashSet<StandbySegment>();
            this.Users = new HashSet<User>();
            this.Vehicles = new HashSet<Vehicle>();
            this.Vehicles1 = new HashSet<Vehicle>();
        }
    
        public int DriverId { get; set; }
        public string DriverHandle { get; set; }
        public string Name { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public Nullable<int> OnDuty { get; set; }
        public Nullable<int> HomeLocationId { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<DriverSchedule> DriverSchedules { get; set; }
        public virtual ICollection<TravelSegment> TravelSegments { get; set; }
        public virtual ICollection<StandbySegment> StandbySegments { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<Vehicle> Vehicles1 { get; set; }
    }
}
