//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.TravelSegments = new HashSet<TravelSegment>();
            this.StandbySegments = new HashSet<StandbySegment>();
        }
    
        public int OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> IsRecurring { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<TravelSegment> TravelSegments { get; set; }
        public virtual ICollection<StandbySegment> StandbySegments { get; set; }
    }
}
