//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStatus
    {
        public VehicleStatus()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int VehicleStatusId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
