//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSchedule
    {
        public VehicleSchedule()
        {
            this.StandbySegments = new HashSet<StandbySegment>();
            this.TravelSegments = new HashSet<TravelSegment>();
        }
    
        public int VehicleScheduleId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> DispatchedBy { get; set; }
        public Nullable<int> BrokerId { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual Dispatcher Dispatcher { get; set; }
        public virtual ICollection<StandbySegment> StandbySegments { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<TravelSegment> TravelSegments { get; set; }
    }
}
