//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.StandbySegments = new HashSet<StandbySegment>();
            this.TravelSegments = new HashSet<TravelSegment>();
            this.VehicleSchedules = new HashSet<VehicleSchedule>();
        }
    
        public int VehicleId { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> StartingMileage { get; set; }
        public Nullable<int> CurrentMileage { get; set; }
        public Nullable<int> HomeLocationId { get; set; }
        public Nullable<int> VehicleStatusId { get; set; }
        public Nullable<int> CurrentDriverId { get; set; }
        public Nullable<int> BrokerOwnerId { get; set; }
        public Nullable<int> VendorOwnerId { get; set; }
        public Nullable<int> CustomerOwnerId { get; set; }
        public Nullable<int> DriverOwnerId { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Driver Driver1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<StandbySegment> StandbySegments { get; set; }
        public virtual ICollection<TravelSegment> TravelSegments { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<VehicleSchedule> VehicleSchedules { get; set; }
    }
}
