//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Dispatchers = new HashSet<Dispatcher>();
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
            this.Users = new HashSet<User>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int VendorId { get; set; }
        public string Name { get; set; }
        public Nullable<int> HomeLocationId { get; set; }
    
        public virtual ICollection<Dispatcher> Dispatchers { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
